### ISSUE TITLE
Incompatibility with Node 18

### ISSUE THREAD

**Issue by Vishal8523** [fivdi/led#3]
Hi,

I am using this led library along with node version 18.13.0 and npm version 9.2.0
Using a raspberry pi based board running debian 12 OS
Getting the following error while performing LED off and on

`{
  message: 'The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)',
  stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (0)\n' +
    '    at Object.writeFileSync (node:fs:2211:5)\n' +
    '    at Led.writeFile (/home/root/app/node_modules/led/led.js:95:13)\n' +
    '    at Led.brightness (/home/root/app/node_modules/led/led.js:43:15)\n' +
    '    at Led.off (/home/root/app/node_modules/led/led.js:25:8)\n' +
    '    at /home/root/app/led.js:519:31\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at /home/root/app/led.js:518:32\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at switchOffLed (/home/root/app/led.js:514:12)\n' +
    '    at process.<anonymous> (/home/root/app/led.js:562:54)',
  toString: [Function: value],
  code: 'ERR_INVALID_ARG_TYPE'
}`

`{
  message: 'The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (255)',
  stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (255)\n' +
    '    at Object.writeFileSync (node:fs:2211:5)\n' +
    '    at Led.writeFile (/home/root/app/node_modules/led/led.js:95:13)\n' +
    '    at Led.brightness (/home/root/app/node_modules/led/led.js:43:15)\n' +
    '    at Led.on (/home/root/app/node_modules/led/led.js:20:8)\n' +
    '    at /home/root/app/led.js:436:27\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at glowRedLed (/home/root/app/led.js:435:18)\n' +
    '    at /home/root/app/led.js:568:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  toString: [Function: value],
  code: 'ERR_INVALID_ARG_TYPE'
}`

This seems to be coming from the led.js library file. The node 18 expects it to be of type string or an instance of Buffer, TypedArray, or DataView. 

Request you to fix this issue for Node 18+ versions.

**Comment by fivdi** [comment]
This issue has been fixed, but an update hasn't been published on npm yet.

**Comment by fivdi** [comment]
The fix is now available on npm with led@1.0.1.
@Vishal8523 Thank you for reporting this issue.
